apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: katasets.mygroup2.mydomain.com
spec:
  group: mygroup2.mydomain.com
  names:
    kind: KataSet
    listKind: KataSetList
    plural: katasets
    singular: kataset
  scope: Namespaced
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      description: KataSet is the Schema for the katasets API
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          description: KataSetSpec defines the desired state of KataSet
          type: object
        status:
          description: KataSetStatus defines the observed state of KataSet
          type: object
      type: object
  version: v1alpha1
  versions:
  - name: v1alpha1
    served: true
    storage: true
